spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/virtualgarage
    username: virtualgarage
    password: password

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:9092

# External service endpoints when running in Docker
external:
  elasticsearch:
    url: http://elasticsearch:9200
    
aws:
  s3:
    endpoint-url: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin

logging:
  level:
    com.virtualgarage: DEBUG
    org.springframework.web: INFO